# fos_rest:
#     view:
#         view_response_listener:  true
#     format_listener:
#         rules:
#             - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }

# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
    param_fetcher_listener: true
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
    body_converter:
        enabled: true
    view:
        view_response_listener: true
        formats: { json: true, xml: false, rss: false }
    # serializer:
    #     serialize_null: true
    # exception:
    #     enabled: true
    #     messages:
    #         Symfony\Component\HttpKernel\Exception\HttpException : true
    #         Symfony\Component\Security\Core\Exception\BadCredentialsException: true
    #     codes:
    #         Symfony\Component\Security\Core\Exception\BadCredentialsException: 401
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
